Repository abnormalbrain/bevy_particle_systems, pull requests merged in 2023-01, with the labels that each got.

#27 Add option to rescale sprites
  src/components.rs
  src/systems.rs
Labels: enhancement

#30 Fix particle color gradients when using texture atlas particles
  assets/projectiles.png
  examples/local_space.rs
  examples/texture_atlas.rs
  src/lib.rs
  src/plugin.rs
  src/systems.rs
Labels: bug

#32 Use distance_squared to compare particle distance
  src/components.rs
  src/systems.rs
Labels: performance
